### ISSUE TITLE
Can't seem to make it work

### ISSUE THREAD

**Issue by itzvenom** [jackeiel/NBA#1]
Hi,

First of all thanks for open source your work.

I've been trying to run it but no luck so far.

Can you make a guide how to run it?

Thanks in advance!

**Comment by jackeiel** [comment]
I’ve written a short usage example in the readme. Without more information I’m not sure I can help. Could you provide some context about where you’re getting hung up?

**Comment by itzvenom** [comment]
Hello again @jackeiel I finally got it, it's working perfectly. Althoght I have a question, from the format: GamePredict('LAC', 'DAL').predict_spread(), which one is the home team? 1st team name or second?
Also..
`>>> GamePredict('LAC', 'DAL').predict_spread()
(6, 12) (6, 12)
(6, 16) (6, 16)
(6, 26) (6, 26)
(6, 21) (6, 21)

Meaning that LAC will win by 6 points?

**Comment by jackeiel** [comment]
Glad to hear! 
And its:
`GamePredict(_home_, _away_).predict_spread()`
